Repository openshift/instaslice-operator, pull requests merged in 2024-09, with the labels that each got.

#38 Wait for GPU operator daemonsets to be created
  deploy/setup.sh
Labels: lgtm

#41 Further simplify deployment in emulator mode
  Makefile
  docs/emulator.md
Labels: lgtm

#39 Update cert manager, Kind node image, README
  README.md
  deploy/setup.sh
  test/e2e/e2e_test.go
Labels: lgtm

#44 Update README.md to point the emulator mode and e2e tests
  README.md
  docs/emulator.md
Labels: lgtm

#47 add acc mem cmd
  docs/emulator.md
Labels: lgtm

#37 Operator-sdk update bundle
  Makefile
  README.md
  bundle/manifests/inference.codeflare.dev_instaslices.yaml
  bundle/manifests/instaslice-operator.clusterserviceversion.yaml
  config/crd/bases/inference.codeflare.dev_instaslices.yaml
  config/manifests/bases/instaslice-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
Labels: lgtm

#72 Fix failures while executing `make test-e2e`
  test/e2e/e2e_test.go
Labels: lgtm

#74 changes for multinode testing
  config/manager/manager.yaml
  docs/multinode_emulator_scale_test.md
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_daemonset.go
  test/perf/kind-cluster/kind-cluster-config.yaml
  test/perf/kind-cluster/mutinode_emulator.sh
  test/perf/load_with_stats.sh
Labels: lgtm

#83 Kueue integration
  internal/controller/instaslice_controller.go
Labels: lgtm

#89 fix gate check
  internal/controller/instaslice_controller.go
Labels: lgtm

#91 move finalizer to controller
  internal/controller/instaslice_controller.go
  internal/controller/pod_webhook.go
  test/e2e/e2e_test.go
Labels: lgtm

#84 add dependabot integration
  .github/dependabot.yml
Labels: lgtm

#85 Patching node memory capacity
  deploy/setup.sh
Labels: lgtm

#111 remove finalizer for failed pods
  internal/controller/instaslice_controller.go
Labels: size/S, lgtm, approved

#114 Adding mamy-cs to owners
  OWNERS
Labels: size/XS

#115 Adding Kevin to owners
  OWNERS
Labels: size/XS

#117 Fix the spelling of word accelerator
  docs/emulator.md
  samples/tf-notebook.yaml
  samples/vllm_pod.yaml
  test/perf/load_with_stats.sh
Labels: size/S, lgtm, approved

#113 Patch the node capacity with GPU memory
  Dockerfile.controller
  Dockerfile.daemonset
  deploy/setup.sh
  internal/controller/instaslice_daemonset.go
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#108 fix capacity update issue
  internal/controller/instaslice_daemonset.go
  internal/controller/instaslice_daemonset_test.go
Labels: lgtm, size/M, approved

#121 fix finalizer and extend res
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/instaslice_daemonset.go
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#135 Add error to result
  internal/controller/instaslice_controller.go
Labels: lgtm, size/XS, approved

#134 Address minor nits
  internal/controller/constants.go
  internal/controller/pod_webhook.go
  internal/controller/pod_webhook_test.go
Labels: size/S, lgtm, approved

#128 Refactor org.instaslice string using the constant
  Dockerfile.controller
  Dockerfile.daemonset
  internal/controller/instaslice_daemonset.go
  internal/controller/instaslice_daemonset_test.go
  internal/controller/pod_webhook.go
  internal/controller/utils.go
  test/e2e/e2e_test.go
  test/utils/constants.go
  test/utils/utils.go
Labels: ok-to-test, lgtm, size/M, approved

#129 Separate finalizer and scheduling gate constants
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
Labels: lgtm, size/M, approved

#130 Enable emulated mode in Openshift 4.18
  Makefile
  config/rbac/instaslice-operator-scc.yaml
  config/rbac/openshift_cluster_role.yaml
  config/rbac/openshift_scc_cluster_role_binding.yaml
  config/webhook/manifests.yaml
  docs/instaslice-emulator-openshift-4.18.md
Labels: lgtm, size/L, approved
