Repository openshift/instaslice-operator, pull requests merged in 2024-11, with the labels that each got.

#214 fixup ocp dockerfile
  Dockerfile.ocp
Labels: size/S, lgtm, approved

#216 Fix enterprise contract errors
  bundle-ocp.Dockerfile
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: ok-to-test, lgtm, size/M, approved

#204 Add NVIDIA driver installation on OpenShift
  README.md
  docs/nvidia-gpu-openshift.md
Labels: lgtm, size/M, approved

#220 use pinned images
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: size/S, lgtm, approved

#228 update readme
  README.md
Labels: size/S, lgtm, approved

#231 set build-source-image to true for all pipelines
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: size/S, lgtm, approved

#232 Support executing e2e tests on an OCP cluster
  Makefile
  docs/e2e-tests-emulator.md
  hack/create-kind-cluster.sh
  hack/deploy-cert-manager.sh
  hack/deploy-instaslice-emulated-on-kind.sh
  hack/deploy-instaslice-emulated-on-ocp.sh
  hack/deploy-kind.sh
  hack/destroy-kind-cluster.sh
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#233 Update bundle v0.0.2
  VERSION
  bundle/manifests/inference.redhat.com_instaslices.yaml
  bundle/manifests/instaslice-operator.clusterserviceversion.yaml
  config/manifests/bases/instaslice-operator.clusterserviceversion.yaml
Labels: lgtm, size/L, approved

#235 push images after building
  Makefile
Labels: lgtm, size/XS, approved

#236 limit which files trigger pipeline runs for which images
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: size/S, lgtm, approved

#238 correct operator image repo name
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
  docs/downstream-builds.yaml
Labels: ok-to-test, lgtm, size/XS, approved

#244 Add downstream container file for deamonset
  Dockerfile.daemonset-ocp
  Makefile
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
  docs/downstream-builds.md
  docs/downstream-builds.yaml
Labels: ok-to-test, lgtm, size/L, approved

#249 use new deamonset-ocp in konflux
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
Labels: ok-to-test, lgtm, size/XS, approved

#246 Move daemonset code in a separate package
  Dockerfile.daemonset
  cmd/daemonset/OWNERS
  cmd/daemonset/main.go
  internal/controller/constants.go
  internal/controller/daemonset/OWNERS
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
  internal/controller/utils.go
Labels: lgtm, size/L, approved

#254 change deamonset path in containerfile
  Dockerfile.daemonset-ocp
Labels: lgtm, size/XS, approved

#255 set hermetic param to true
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: size/S, ok-to-test, lgtm, approved

#259 add customizations back for daemonset after a pipeline refresh
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
Labels: size/S, ok-to-test, lgtm, approved

#260 Enable multi arch for deamonset
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: ok-to-test, lgtm, size/XS, approved

#263 limit triggers to related files
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: ok-to-test, lgtm, size/M, approved

#268 Revert "limit triggers to related files"
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: ok-to-test, lgtm, size/M, approved

#272 fix max slice creation per GPU
  internal/controller/capacity.go
  internal/controller/daemonset/instaslice_daemonset.go
Labels: lgtm, do-not-merge/hold, size/XS, approved

#264 Implement packing at GPU dimension
  internal/controller/capacity.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  test/e2e/e2e_test.go
Labels: lgtm, do-not-merge/hold, size/M, approved

#274 Refactor code while updating instaslice allocations
  Dockerfile.daemonset
  Dockerfile.daemonset-ocp
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/instaslice_controller.go
  internal/controller/utils/utils.go
Labels: lgtm, size/L, approved

#281 update daemonset pullspecs
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: ok-to-test, lgtm, size/XS, approved

#286 Add unit tests for the daemonset
  internal/controller/constants.go
  internal/controller/daemonset/OWNERS
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
Labels: lgtm, size/L, approved
