Repository openshift/instaslice-operator, pull requests merged in 2024-10, with the labels that each got.

#138 Fix the makefile target for openshift emulated mode
  Makefile
Labels: lgtm, size/XS, approved

#152 Add license file
  LICENSE
Labels: lgtm, size/L, approved

#142 Add tests for Instaslice Controller
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
Labels: size/XL, lgtm, approved

#159 add cpmeadors owners
  OWNERS
Labels: lgtm, size/XS, approved

#154 Fix failures while running `make test-e2e`
  Makefile
  config/manager/manager.yaml
  test/e2e/e2e_test.go
Labels: size/S, lgtm, approved

#158 add rphillips to approvers
  OWNERS
Labels: lgtm, size/XS, approved

#160 update linter due to deprecated exportloopref
  .golangci.yml
Labels: lgtm, size/XS, approved

#162 Create new slice for each allocation
  internal/controller/instaslice_daemonset.go
  test/daemonset_testing_scripts/test_fire80shortjobs_tocompletion.sh
  test/daemonset_testing_scripts/test_longrunning_host_mig_count.sh
Labels: lgtm, size/L, approved

#149 Refactor and configure zap logger
  cmd/controller/main.go
  cmd/daemonset/main.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_daemonset.go
Labels: ok-to-test, lgtm, size/L, approved

#163 Remove code for the capacity update hack
  deploy/custom-configmapwithprofiles.yaml
  deploy/setup.sh
Labels: size/S, lgtm, approved

#169 remove dangling slice
  internal/controller/instaslice_daemonset.go
Labels: lgtm, size/M, approved

#170 simplify code to use mig walk
  internal/controller/instaslice_daemonset.go
Labels: lgtm, size/L, approved

#161 Install Daemonset by controller and sdk bundle update
  Makefile
  VERSION
  bundle/manifests/inference.codeflare.dev_instaslices.yaml
  bundle/manifests/instaslice-operator.clusterserviceversion.yaml
  config/emulator/controller-with-emulator.yaml
  config/emulator/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/instaslice-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
  test/e2e/e2e_test.go
Labels: size/XL, lgtm, approved

#172 rem get alloc call
  internal/controller/instaslice_daemonset.go
Labels: lgtm, size/M, approved

#171 simplify patch node code daemonset
  internal/controller/instaslice_daemonset.go
Labels: size/S, lgtm, approved

#174 Add a namespace selector to instaslice webhook
  README.md
  bundle/manifests/inference.codeflare.dev_instaslices.yaml
  config/default/kustomization.yaml
  config/default/namespace_selector_patch.yaml
  config/rbac/openshift_scc_cluster_role_binding.yaml
  config/webhook/manifests.yaml
  docs/emulator.md
  internal/controller/constants.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
  test/e2e/e2e_test.go
  test/perf/kind-cluster/mutinode_emulator.sh
Labels: lgtm, size/M, approved

#181 remove internal slice cache
  internal/controller/instaslice_daemonset.go
Labels: lgtm, size/L, approved

#180 Clean up daemonset deploy logic and update unit tests
  Makefile
  config/manager/manager.yaml
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/instaslice_daemonset.go
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#184 implementation to remove prepared
  api/v1alpha1/instaslice_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/inference.codeflare.dev_instaslices.yaml
  internal/controller/capacity.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_daemonset.go
  test/e2e/e2e_test.go
  test/e2e/resources/instaslice-fake-capacity.yaml
Labels: lgtm, size/L, approved

#194 miscellaneous fixes for demo
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/instaslice_daemonset.go
  internal/controller/pod_webhook.go
  test/e2e/e2e_test.go
  test/e2e/resources/instaslice-fake-capacity.yaml
Labels: lgtm, size/L, approved

#203 initial refactor of kind e2e tests
  .gitignore
  .ignore
  Dockerfile.controller
  Makefile
  deploy/setup.sh
  hack/create_kind_cluster.sh
  hack/deploy-kind.sh
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/resources/instaslice-fake-capacity.yaml.tmpl
Labels: lgtm, size/L, approved

#205 Fix the daemonset crashing
  internal/controller/instaslice_daemonset.go
Labels: lgtm, size/XS, approved

#210 update readme for kind e2e
  README.md
Labels: size/S, lgtm, approved

#211 fix slice deletion issue
  internal/controller/instaslice_daemonset.go
Labels: size/S, lgtm, approved
