Repository openshift/instaslice-operator, pull requests merged in 2024-12, with the labels that each got.

#287 select mig enabled gpus only
  internal/controller/daemonset/instaslice_daemonset.go
  test/daemonset_testing_scripts/test_gpu_filtering.sh
Labels: lgtm, size/M, approved

#299 remove GPU count hardcoding
  test/e2e/e2e_test.go
Labels: lgtm, size/XS, approved

#298 add wait for all images to be completed before creating bundle
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/wait-for-image-task.yaml
Labels: lgtm, size/M, approved

#306 Do not install upstream cert manager with OCP
  Makefile
Labels: lgtm, size/XS, approved

#311 Add focus to e2e to filter the test cases
  Makefile
Labels: lgtm, size/XS, approved

#308 Add steps to list prerequisites for running e2e in OCP
  docs/e2e-tests-emulator.md
Labels: lgtm, size/M, approved

#309 Do not delete the namespace explicitly in cleanup
  Makefile
Labels: lgtm, size/XS, approved

#312 Revert "add wait for all images to be completed before creating bundle"
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/wait-for-image-task.yaml
Labels: lgtm, size/M, approved

#314 set security context for controller deployment
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#315 add config type
  cmd/controller/main.go
  cmd/daemonset/main.go
  internal/controller/config/config.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
Labels: lgtm, size/L, approved

#323 Revert "add config type (#315)"
  cmd/controller/main.go
  cmd/daemonset/main.go
  internal/controller/config/config.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
Labels: lgtm, size/L, approved

#320 Refactor e2e to use controller runtime golang client
  Makefile
  internal/controller/constants.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  test/e2e/e2e_test.go
  test/e2e/resources/instaslice-fake-capacity.yaml.tmpl
  test/e2e/resources/resource_generator.go
  test/e2e/resources/test-finalizer.yaml
  test/e2e/resources/test-pod-no-requests.yaml
  test/e2e/resources/test-pod-with-large-cpu-requests.yaml
  test/e2e/resources/test-pod-with-large-memory-requests.yaml
  test/e2e/resources/test-pod-with-small-requests.yaml
  test/e2e/resources/test-sleep-deployment.yaml
  test/e2e/resources/test-sleep-job.yaml
  test/e2e/resources/test-sleep-statefulset.yaml
  test/e2e/resources/test_multiple_pods.yaml
Labels: lgtm, size/XXL, approved

#324 Add config type
  cmd/controller/main.go
  cmd/daemonset/main.go
  internal/controller/config/config.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
Labels: lgtm, size/L, approved

#326 e2e: Print the node name after it is set
  test/e2e/e2e_test.go
Labels: size/S, lgtm, approved

#327 daemonset: only init nvml once
  cmd/daemonset/main.go
  internal/controller/daemonset/instaslice_daemonset.go
Labels: lgtm, size/L, approved

#328 Avoid duplication while transforming resources
  internal/controller/pod_webhook.go
  internal/controller/pod_webhook_test.go
Labels: lgtm, size/L, approved

#335 Clarify NVIDIA GPU operator's MIG manager settings
  docs/nvidia-gpu-openshift.md
Labels: lgtm, size/XS, approved

#237 deploy operator using integration tests in konflux
  .tekton/integration-tests/deploy-operator.yaml
Labels: ok-to-test, lgtm, size/L, approved

#342 Document disabling CUDA validator
  docs/nvidia-gpu-openshift.md
Labels: lgtm, size/L, approved

#345 konflux: use m5.xlarge and install bundle timeout to 30 minutes
  .tekton/integration-tests/deploy-operator.yaml
Labels: lgtm, size/XS, approved

#341 Use sha kube rbac proxy
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#348 resolve CVE-2024-45338
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: lgtm, size/XXL, approved
