Repository openshift/instaslice-operator, pull requests merged in 2025-04, with the labels that each got.

#506 Add shell and unicode sast pipeline tasks
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: lgtm, size/L, approved

#513 makefile: bump deploy nfd and nvidia timeouts to 5 minutes
  Makefile
Labels: lgtm, size/XS, approved

#516 makefile: fix nfd and nvidia install
  Makefile
Labels: lgtm, size/XS, approved

#517 makefile: wait for creation of CRDs
  Makefile
Labels: lgtm, size/XS, approved

#507 Decouple daemonset creation and move to setupwithmanager
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
Labels: size/XL, lgtm, approved

#518 makefile: add targets without waits
  Makefile
Labels: size/S, lgtm, approved

#519 makefile: ocp: convert to shell scripts for nfd and nvidia deployment
  Makefile
  hack/deploy-nfd.sh
  hack/deploy-nvidia.sh
Labels: lgtm, size/L, approved

#520 bump timeouts to 10 minutes for nfd and nvidia scripts
  hack/deploy-nfd.sh
  hack/deploy-nvidia.sh
Labels: lgtm, size/XS, approved

#521 use our _kubectl wrapper within deploy-nfd and deploy-nvidia.sh
  hack/deploy-nfd.sh
  hack/deploy-nvidia.sh
Labels: lgtm, size/XS, approved

#525 add renovate file
  renovate.json
Labels: lgtm, size/M, approved

#522 Add Pod filtering and webhook annotation
  README.md
  config/webhook/kustomization.yaml
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
  internal/controller/pod_webhook_test.go
  test/e2e/e2e_test.go
  test/e2e/resources/resource_generator.go
Labels: ok-to-test, lgtm, size/L, approved

#533 konflux e2e: checkout the PR source
  .tekton/integration-tests/deploy-operator.yaml
Labels: lgtm, size/XS, approved

#534 build the bundle all the time with PRs and use pr numbers for image names
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-pull-request.yaml
Labels: lgtm, size/XS, approved

#536 exclude vendor and test directories from instaslice for synk
  .snyk
Labels: lgtm, size/XS, approved

#542 add lgtm/approve to automerge settings
  renovate.json
Labels: lgtm, size/XS, approved
