Repository openshift/instaslice-operator, pull requests merged in 2025-09, with the labels that each got.

#942 chore(KONFLUX-6210): fix and set name and cpe label for instaslice-daemonset-next
  Dockerfile.daemonset.ocp
Labels: lgtm, size/XS, approved

#944 chore(KONFLUX-6210): fix and set name and cpe label for instaslice-scheduler-next
  Dockerfile.scheduler.ocp
Labels: lgtm, size/XS, approved

#943 chore(KONFLUX-6210): fix and set name and cpe label for instaslice-operator-next
  Dockerfile.ocp
Labels: lgtm, size/XS, approved

#945 chore(KONFLUX-6210): fix and set name and cpe label for instaslice-webhook-next
  Dockerfile.webhook.ocp
Labels: lgtm, size/XS, approved

#946 chore(KONFLUX-6210): fix and set name and cpe label for instaslice-operator-bundle-next
  bundle-ocp.Dockerfile
Labels: lgtm, size/XS, approved

#956 OCPBUGS-61931: Fix incorrect prereq description in CSV
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  deploy/base-csv/das-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-bug, jira/valid-reference, size/L, approved

#924 Ensure the dockerfiles are built for dev purpose from non-x86 arch
  Justfile
  hack/deploy-das-ocp.sh
Labels: size/S, lgtm, approved

#958 Remove unsupported features
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  deploy/base-csv/das-operator.clusterserviceversion.yaml
Labels: size/S, lgtm, approved
