Repository openshift/instaslice-operator, pull requests merged in 2025-02, with the labels that each got.

#404 add tasks to deploy-operator pipeline to run e2e tests
  .tekton/integration-tests/deploy-operator.yaml
  Makefile
  bundle-ocp/manifests/inference.redhat.com_instaslices.yaml
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
  hack/emulator_mode-patch.json
Labels: ok-to-test, lgtm, size/L, approved

#418 API refactor to improve resource representation and state transitions
  api/v1alpha1/instaslice_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle-ocp/manifests/inference.redhat.com_instaslices.yaml
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
  bundle-ocp/manifests/manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/crd/bases/inference.redhat.com_instaslices.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  internal/controller/capacity.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/utils/emulated.go
  internal/controller/utils/utils.go
  samples/test-statefulset.yaml
  test/e2e/e2e_test.go
  test/e2e/resources/resource_generator.go
Labels: lgtm, size/XXL, approved

#432 update README with installation instruction for OCP in DP
  README.md
Labels: size/S, lgtm, approved

#440 remove ecosystem-cert-preflight-check from bundle pipelines
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: ok-to-test, lgtm, size/M, approved

#443 fix daemonset image url
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: size/S, ok-to-test, lgtm, approved

#460 update go vers to 1.23
  Dockerfile.daemonset-ocp
  Dockerfile.ocp
  go.mod
Labels: lgtm, size/XS, approved

#463 use go 1.23 image for e2e tests
  .tekton/integration-tests/deploy-operator.yaml
Labels: lgtm, size/XS, approved
