Repository openshift/instaslice-operator, pull requests merged in 2025-03, with the labels that each got.

#353 Add instaslice custom metrics
  api/v1alpha1/instaslice_types.go
  cmd/controller/main.go
  config/crd/bases/inference.redhat.com_instaslices.yaml
  config/manager/manager.yaml
  deploy/instaslice-metrics-service.yaml
  deploy/instaslice-servicemonitor.yaml
  deploy/prometheus-role.yaml
  deploy/prometheus-rolebinding.yaml
  deploy/prometheus-serviceaccount.yaml
  deploy/prometheus.yaml
  internal/controller/capacity.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/metrics.go
  internal/controller/prometheus_manager.go
  internal/controller/prometheus_manager_test.go
Labels: size/XL, lgtm, approved

#470 Revert "Add instaslice custom metrics"
  api/v1alpha1/instaslice_types.go
  cmd/controller/main.go
  config/crd/bases/inference.redhat.com_instaslices.yaml
  config/manager/manager.yaml
  deploy/instaslice-metrics-service.yaml
  deploy/instaslice-servicemonitor.yaml
  deploy/prometheus-role.yaml
  deploy/prometheus-rolebinding.yaml
  deploy/prometheus-serviceaccount.yaml
  deploy/prometheus.yaml
  internal/controller/capacity.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/metrics.go
  internal/controller/prometheus_manager.go
  internal/controller/prometheus_manager_test.go
Labels: size/XL, lgtm, approved

#441 Handle incorrect allocations in the system
  Makefile
  internal/controller/cache.go
  internal/controller/capacity.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/instaslice_controller.go
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#472 [Updated] Add custom metrics
  cmd/controller/main.go
  config/manager/manager.yaml
  deploy/instaslice-metrics-service.yaml
  deploy/instaslice-servicemonitor.yaml
  deploy/prometheus-role.yaml
  deploy/prometheus-rolebinding.yaml
  deploy/prometheus-serviceaccount.yaml
  deploy/prometheus.yaml
  docs/enable-promethues-metrics.md
  internal/controller/cache.go
  internal/controller/capacity.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/metrics.go
  internal/controller/prometheus_manager.go
  internal/controller/prometheus_manager_test.go
Labels: size/XL, lgtm, approved

#485 added make targets for dependencies of e2e tests on ocp
  Makefile
  hack/manifests/cert-manager-rh.yaml
  hack/manifests/gpu-cluster-policy.yaml
  hack/manifests/nfd-instance.yaml
  hack/manifests/nfd.yaml
  hack/manifests/nvidia-cpu-operator.yaml
Labels: ok-to-test, lgtm, size/L, approved

#433 OCPNODE-3015: Support node reboots
  Makefile
  api/v1alpha1/instaslice_types.go
  bundle-ocp/manifests/inference.redhat.com_instaslices.yaml
  config/crd/bases/inference.redhat.com_instaslices.yaml
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/utils/emulated.go
  test/e2e/e2e_test.go
Labels: lgtm, jira/valid-reference, size/L, approved

#491 add checks to deploy operator make targets
  Makefile
Labels: ok-to-test, lgtm, size/XS, approved

#498 Update the cache only upon the Instaslice object update
  internal/controller/instaslice_controller.go
Labels: lgtm, size/XS, approved
