Repository openshift/instaslice-operator, pull requests merged in 2025-08, with the labels that each got.

#847 deploy scripts cleanup
  hack/deploy-nfd.sh
  hack/deploy-nvidia.sh
  hack/manifests/nvidia-gpu-operator.yaml
Labels: lgtm, size/XS, approved

#859 remove "" from apiGroups for events
  bindata/assets/instaslice-operator/scheduler_rbac.clusterrole.yaml
Labels: lgtm, size/XS, approved

#863 add suggested namespace
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  deploy/base-csv/das-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#874 OCPNODE-3451: bundle: update icon to be Red Hat logo, and provider to be Red Hat
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  bundle-ocp/metadata/annotations.yaml
  deploy/base-csv/das-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, size/M, approved

#895 OCPNODE-3550: Update licence to reflect das-operator
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  deploy/base-csv/das-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, jira/valid-reference, approved
