Repository openshift/instaslice-operator, pull requests merged in 2025-01, with the labels that each got.

#358 add allocation status e2e
  Makefile
  test/e2e/e2e_test.go
Labels: size/S, lgtm, approved

#362 remove update call and move to patch for adding updates to InstaSlice object
  internal/controller/instaslice_controller.go
  internal/controller/utils/utils.go
Labels: lgtm, size/M, approved

#363 Enable running e2e on GPU using OCP
  Makefile
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#368 separate image references to eliminate conflict.
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
Labels: ok-to-test, lgtm, size/XS, approved

#366 add daemonset e2e test
  test/e2e/e2e_test.go
  test/e2e/resources/resource_generator.go
Labels: lgtm, size/L, approved

#376 remove daemonset shell scripts
  test/daemonset_testing_scripts/test_fire80shortjobs_tocompletion.sh
  test/daemonset_testing_scripts/test_gpu_filtering.sh
  test/daemonset_testing_scripts/test_longrunning_host_mig_count.sh
Labels: lgtm, size/L, approved

#379 Decouple e2e invocation in ocp from operator installation
  Makefile
Labels: lgtm, size/XS, approved

#364 update make files to to allow automated integration tests to use them
  Makefile
  config/manager/manager.yaml
  config/manifests-ocp-emulated/bases/instaslice-operator.clusterserviceversion.yaml
  config/manifests-ocp-emulated/kustomization.yaml
  config/manifests-ocp/bases/instaslice-operator.clusterserviceversion.yaml
  config/manifests-ocp/kustomization.yaml
  config/ocp-emulated/controller-with-emulator.yaml
  config/ocp-emulated/kustomization.yaml
  config/ocp/kustomization.yaml
  config/rbac-ocp/instaslice-operator-scc.yaml
  config/rbac-ocp/kustomization.yaml
  config/rbac-ocp/openshift_cluster_role.yaml
  config/rbac-ocp/openshift_scc_cluster_role_binding.yaml
  docs/downstream-builds.md
  hack/label-node.sh
  hack/manifests/cert-manager-rh.yaml
Labels: size/XL, ok-to-test, lgtm, approved

#354 Fetch the GPU memory from the `nvml` lib api
  internal/controller/constants.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  test/e2e/e2e_test.go
Labels: lgtm, size/L, approved

#399 Programmatically install SCC on OpenShift
  Dockerfile.controller
  Dockerfile.daemonset
  Dockerfile.daemonset-ocp
  Dockerfile.ocp
  Makefile
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
  bundle-ocp/manifests/manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/instaslice-operator.clusterserviceversion.yaml
  cmd/controller/main.go
  cmd/daemonset/main.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/config/config.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/daemonset/instaslice_daemonset_test.go
  internal/controller/instaslice_controller.go
  internal/controller/manifests/manifests.go
  internal/controller/utils/emulated.go
  internal/controller/utils/utils.go
  test/e2e/e2e_test.go
  test/e2e/resources/resource_generator.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/manifestival/controller-runtime-client/.gitignore
  vendor/github.com/manifestival/controller-runtime-client/LICENSE
  vendor/github.com/manifestival/controller-runtime-client/README.md
  vendor/github.com/manifestival/controller-runtime-client/client.go
  vendor/github.com/manifestival/manifestival/.gitignore
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/LICENSE
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/internal/overlay/overlay.go
  vendor/github.com/manifestival/manifestival/internal/patch/patch.go
  vendor/github.com/manifestival/manifestival/internal/sources/path.go
  vendor/github.com/manifestival/manifestival/internal/sources/yaml.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#397 rename error variables
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/instaslice_controller.go
  test/e2e/resources/resource_generator.go
Labels: lgtm, size/M, approved

#402 use bundle image in ocp-deploy make target
  Makefile
Labels: size/S, lgtm, approved

#396 separate manager config for upstream and downstream
  Makefile
  bundle.Dockerfile
  config/manager-ocp/kustomization.yaml
  config/manager-ocp/manager.yaml
  config/ocp-emulated/kustomization.yaml
  config/ocp/kustomization.yaml
Labels: ok-to-test, lgtm, size/L, approved

#400 fix for kal linter
  api/v1alpha1/instaslice_types.go
  config/crd/bases/inference.redhat.com_instaslices.yaml
  internal/controller/capacity.go
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/utils/emulated.go
Labels: lgtm, size/L, approved

#405 aggregate update and delete calls with cleanup
  internal/controller/daemonset/instaslice_daemonset.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/utils.go
  internal/controller/utils/utils.go
Labels: lgtm, size/M, approved

#409 wait to complete deletion slice before creating slice
  internal/controller/daemonset/instaslice_daemonset.go
Labels: size/S, lgtm, approved

#412 operator: imagePullPolicy to always
  config/manager-ocp/manager.yaml
Labels: lgtm, size/XS, approved
