Repository openshift/instaslice-operator, pull requests merged in 2025-05, with the labels that each got.

#553 Revert "Add Pod filtering and webhook annotation"
  README.md
  config/webhook/kustomization.yaml
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/pod_webhook.go
  internal/controller/pod_webhook_test.go
  test/e2e/e2e_test.go
  test/e2e/resources/resource_generator.go
Labels: lgtm, size/L, approved

#555 use on-cel-expression to limit which images are triggered by konflux
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
Labels: lgtm, size/M, approved

#547 Clean up node object
  Makefile
  README.md
  bundle-ocp/manifests/instaslice-operator.clusterserviceversion.yaml
  config/emulator/controller-with-emulator.yaml
  config/manager-ocp/manager.yaml
  internal/controller/config/config.go
  internal/controller/constants.go
  internal/controller/instaslice_controller.go
  internal/controller/instaslice_controller_test.go
  internal/controller/utils/utils.go
Labels: size/XL, lgtm, approved

#557 Konflux build pipeline service account migration for instaslice-opera…
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
Labels: lgtm, size/L, approved

#561 remove dependabot in favor of renovate
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#563 disable renovate updates for go mod
  renovate.json
Labels: lgtm, size/XS, approved

#567 Fix `make deploy` failure
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#572 remove old api directory
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/instaslice_types.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: size/XL, approved

#573 add manifests folder
  manifests/inference.redhat.com_instaslices.yaml
  manifests/instaslice-operator.crd.yaml
Labels: size/XL, approved

#574 add deploy directory and run make generate
  Dockerfile.daemonset-ocp
  deploy/00_instaslice-operator.crd.yaml
  deploy/00_instaslices.crd.yaml
  deploy/01_namespace.yaml
  deploy/02_00_operand_clusterrole.yaml
  deploy/02_01_operand_clusterrolebinding.yaml
  deploy/02_02_operand_role.yaml
  deploy/02_03_operand_rolebinding.yaml
  deploy/04_01_clusterrole.yaml
  deploy/04_02_clusterrolebinding.yaml
  deploy/04_serviceaccount.yaml
  deploy/05_deployment.yaml
  deploy/09_instaslice_operator.cr.yaml
  deploy/instaslice-metrics-service.yaml
  deploy/instaslice-servicemonitor.yaml
  deploy/prometheus-role.yaml
  deploy/prometheus-rolebinding.yaml
  deploy/prometheus-serviceaccount.yaml
  deploy/prometheus.yaml
  deploy/setup.sh
  openapi.json
  pkg/generated/applyconfiguration/instasliceoperator/v1alpha1/instasliceoperatorspec.go
Labels: size/XXL, approved

#575 add makefile targets
  Makefile
  deploy/09_instaslice_operator.cr.yaml
Labels: size/S, approved

#581 fix image registry
  Makefile
Labels: size/S, approved

#582 fix run images
  Dockerfile.ocp
  Dockerfile.webhook.ocp
Labels: size/XS, approved

#586 Add on cel expression file filters
  .tekton/instaslice-daemonset-next-pull-request.yaml
  .tekton/instaslice-daemonset-next-push.yaml
  .tekton/instaslice-daemonset-pull-request.yaml
  .tekton/instaslice-daemonset-push.yaml
  .tekton/instaslice-operator-bundle-next-pull-request.yaml
  .tekton/instaslice-operator-bundle-next-push.yaml
  .tekton/instaslice-operator-bundle-pull-request.yaml
  .tekton/instaslice-operator-bundle-push.yaml
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
  .tekton/instaslice-operator-pull-request.yaml
  .tekton/instaslice-operator-push.yaml
  .tekton/instaslice-webhook-next-pull-request.yaml
  .tekton/instaslice-webhook-next-push.yaml
Labels: lgtm, size/XXL, approved

#589 add related_images.json to tekton
  .tekton/instaslice-daemonset-next-push.yaml
  .tekton/instaslice-operator-next-push.yaml
  .tekton/instaslice-webhook-next-push.yaml
  related_images.json
Labels: size/S, lgtm, approved

#590 set hermetic and build-source-image to true
  .tekton/instaslice-daemonset-next-pull-request.yaml
  .tekton/instaslice-daemonset-next-push.yaml
  .tekton/instaslice-operator-bundle-next-pull-request.yaml
  .tekton/instaslice-operator-bundle-next-push.yaml
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
  .tekton/instaslice-webhook-next-pull-request.yaml
  .tekton/instaslice-webhook-next-push.yaml
Labels: lgtm, size/M, approved

#600 removed extra quote in on-cel-expression
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
Labels: lgtm, size/XS, approved

#601 Test nudges and add relatedImages to CSV
  bundle-ocp/manifests/kustomize.yaml
  config/manifests-ocp/bases/instaslice-operator.clusterserviceversion.yaml
  pkg/version/version.go
Labels: size/S, lgtm, approved

#603 seed the initial related_images
  related_images.json
Labels: lgtm, size/XS, approved

#605 create bundle on related_images.json change and fix circular dependency
  .tekton/instaslice-operator-bundle-next-pull-request.yaml
  .tekton/instaslice-operator-bundle-next-push.yaml
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
Labels: lgtm, size/XS, approved

#607 test nudges
  pkg/daemonset/daemonset.go
  pkg/webhook/webhook.go
Labels: lgtm, size/XS, approved
