Repository openshift/instaslice-operator, pull requests merged in 2025-07, with the labels that each got.

#627 renovate: run renovate more often
  renovate.json
Labels: size/S, lgtm, approved

#646 fix enterprise contracts
  .tekton/instaslice-scheduler-next-pull-request.yaml
  .tekton/instaslice-scheduler-next-push.yaml
Labels: lgtm, size/XS, approved

#650 Revert "renovate: run renovate more often"
  renovate.json
Labels: lgtm, size/XS, approved

#651 bump golangci-lint
  Makefile
Labels: lgtm, size/XS, approved

#645 Manually update konflux updates - july 1st
  .tekton/instaslice-daemonset-next-pull-request.yaml
  .tekton/instaslice-daemonset-next-push.yaml
  .tekton/instaslice-operator-bundle-next-pull-request.yaml
  .tekton/instaslice-operator-bundle-next-push.yaml
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
  .tekton/instaslice-webhook-next-pull-request.yaml
  .tekton/instaslice-webhook-next-push.yaml
Labels: lgtm, size/L, approved

#657 remove golangci-lint
  .tekton/instaslice-golangci-lint.yaml
Labels: lgtm, size/M, approved

#662 regenerate bundle fixes
  Makefile
  bundle-ocp.Dockerfile
  bundle-ocp/manifests/das-operator-operand_rbac.authorization.k8s.io_v1_role.yaml
  bundle-ocp/manifests/das-operator-operand_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle-ocp/manifests/das-operator-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  bundle-ocp/manifests/das-scheduler-authentication-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/manifests/das-scheduler-config_v1_configmap.yaml
  bundle-ocp/manifests/das-scheduler-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/manifests/dup0_das-operator-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/manifests/inference.redhat.com_allocationclaims.yaml
  bundle-ocp/manifests/inference.redhat.com_dasoperators.yaml
  bundle-ocp/manifests/inference.redhat.com_nodeaccelerators.yaml
  bundle-ocp/metadata/annotations.yaml
  bundle.Dockerfile
  bundle/manifests/inference.redhat.com_instasliceoperators.yaml
  bundle/manifests/inference.redhat.com_instaslices.yaml
  bundle/manifests/instaslice-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/instaslice-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/instaslice-operator-operand_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/instaslice-operator-operand_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/instaslice-operator-operand_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/instaslice-operator-system:openshift:scc:privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/instaslice-operator-webhook-service_v1_service.yaml
  bundle/manifests/instaslice-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  deploy/00_inference.redhat.com_allocationclaims.crd.yaml
  deploy/04_deployment.yaml
  deploy/05_scheduler_deployment.yaml
  deploy/das-operator.clusterserviceversion.yaml
  deploy/inference.redhat.com_allocationclaims.yaml
Labels: lgtm, size/XXL, approved

#665 remove hard coded reference to docker binary
  Makefile
Labels: lgtm, size/M, approved

#666 remove references to CONTAINER_TOOL from Makefile
  Makefile
Labels: lgtm, size/XS, approved

#668 remove reference to scheduler deployment yaml from Makefile
  Makefile
Labels: lgtm, size/XS, approved

#670 add the component name to the image name
  .tekton/instaslice-operator-bundle-next-pull-request.yaml
  .tekton/instaslice-operator-bundle-next-push.yaml
  related_images.json
Labels: size/S, lgtm, approved

#676 generate bundle from a base csv
  Makefile
  bundle-ocp/manifests/das-operator-operand_rbac.authorization.k8s.io_v1_role.yaml
  bundle-ocp/manifests/das-operator-operand_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  bundle-ocp/manifests/das-scheduler-authentication-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/manifests/das-scheduler-config_v1_configmap.yaml
  bundle-ocp/manifests/das-scheduler-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/metadata/annotations.yaml
  bundle-ocp/tests/scorecard/config.yaml
  deploy/02_operand_rbac.yaml
  deploy/02_operator_rbac.yaml
  deploy/das-operator.clusterserviceversion.yaml
Labels: lgtm, size/XXL, approved

#682 move the base csv to a sub folder
  deploy/base-csv/das-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#684 Use internal RH registry and create scaffolding to preserve the developer registry images
  .tekton/instaslice-daemonset-next-push.yaml
  .tekton/instaslice-operator-next-push.yaml
  .tekton/instaslice-scheduler-next-push.yaml
  .tekton/instaslice-webhook-next-push.yaml
  bundle.developer.Dockerfile
  related_images.developer.json
  related_images.json
Labels: lgtm, size/M, approved

#683 add authentication reader role to the operator
  bundle-ocp/manifests/das-operator-authentication-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  deploy/02_operator_rbac.yaml
Labels: size/S, lgtm, approved

#690 fix run local for custom image
  Makefile
  deploy/02_privileged_scc_binding.yaml
Labels: size/S, lgtm, approved

#692 fix the developer bundle
  bundle.developer.Dockerfile
Labels: lgtm, size/XS, approved

#694 remove the sast-coverity-check to speed up builds
  .tekton/instaslice-operator-bundle-developer-next-pull-request.yaml
  .tekton/instaslice-operator-bundle-developer-next-push.yaml
Labels: lgtm, size/L, approved

#693 add justfile and start removing logic from makefile
  Justfile
  Makefile
  README.md
  renovate.json
Labels: lgtm, size/L, approved

#711 cleanup justfile and add more functionality
  .markdownlint.json
  Justfile
  Makefile
  README.md
  related_images.developer.json
Labels: size/XL, lgtm, approved

#714 cleanup the makefile and test nudging
  Makefile
Labels: size/S, lgtm, approved

#720 pass the kubeconfig to run-local
  Justfile
Labels: size/S, lgtm, approved

#721 Justfile: wait for CRDs before applying other resources
  Justfile
  hack/deploy-das-ocp.sh
Labels: lgtm, size/M, approved

#726 Minor fix to Justfile to avoid shell() function
  Justfile
Labels: size/S, lgtm, approved

#728 add comment to makefile
  Makefile
Labels: lgtm, size/XS, approved

#734 fix scheduler pushes because of typo
  .tekton/instaslice-scheduler-next-push.yaml
Labels: lgtm, size/XS, approved

#735 more cleanup of the makefile
  Makefile
Labels: lgtm, size/XS, approved

#709 OCPNODE-3419: deploy: add example DASOperator object for operator-sdk
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  bundle-ocp/metadata/annotations.yaml
  deploy/05_nodeaccelerators.cr.yaml
  deploy/06_allocationclaims.cr.yaml
Labels: lgtm, jira/valid-reference, size/M, approved

#743 bump all images
  Makefile
Labels: lgtm, size/XS, approved

#724 add env debug to the just info target
  Justfile
Labels: size/S, lgtm, approved

#748 fix regex for dockerfiles in renovate
  renovate.json
Labels: lgtm, size/XS, approved

#750 remove old unused dockerfiles
  Dockerfile
  Dockerfile.daemonset
  Dockerfile.webhook
Labels: lgtm, size/M, approved

#754 Create a single target to deploy pre-reqs, das and execute e2e tests
  Justfile
Labels: lgtm, size/XS, approved

#756 Add a target to create a related_images json file
  Justfile
Labels: size/S, lgtm, approved

#764 Possible resolution to the RBAC issue while executing e2e tests in CI
  test/e2e/e2e.go
Labels: size/S, lgtm, approved

#763 Enable leader election in secondary scheduler
  bindata/assets/instaslice-operator/scheduler_config.yaml
  bindata/assets/instaslice-operator/scheduler_rbac.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_cluster_role.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_cluster_role_binding.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_reader_cluster_role.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_reader_cluster_role_binding.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_reader_cr.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_reader_crb.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_reader_rb.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_role.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_role_binding.yaml
  bindata/assets/instaslice-operator/scheduler_rbac_service_account.yaml
  pkg/cmd/scheduler/cmd.go
  pkg/operator/target_config_reconciler.go
Labels: lgtm, size/L, approved

#767 * : address rbac permissions issue with scheduler and fix daemonset race
  deploy/03_scheduler_rbac.yaml
  hack/deploy-das-ocp.sh
  pkg/daemonset/deviceplugins/discovery.go
  pkg/operator/target_config_reconciler.go
Labels: lgtm, size/L, approved

#775 cleanup justfile and add groups
  .editorconfig
  .gitignore
  Justfile
  hack/create-kind-cluster.sh
  hack/deploy-cert-manager.sh
  hack/deploy-das-ocp.sh
  hack/deploy-instaslice-emulated-on-kind.sh
  hack/deploy-instaslice-emulated-on-ocp.sh
  hack/deploy-nfd.sh
  hack/deploy-nvidia.sh
  hack/destroy-kind-cluster.sh
  hack/label-node.sh
  hack/run-local.sh
  hack/run-locally.sh
  hack/update-codegen.sh
  hack/update-instaslice-controller-manifests.sh
  hack/verify-codegen.sh
  hack/verify-gofmt.sh
  hack/wait-for-instaslice.sh
Labels: size/XL, lgtm, approved

#776 Revert "OCPNODE-3419: deploy: add example DASOperator object for operator-sdk"
  bundle-ocp/manifests/das-operator.clusterserviceversion.yaml
  bundle-ocp/metadata/annotations.yaml
  deploy/05_nodeaccelerators.cr.yaml
  deploy/06_allocationclaims.cr.yaml
Labels: lgtm, jira/valid-reference, size/M, approved

#781 make the webhook mandatory
  bindata/assets/instaslice-operator/webhook.yaml
Labels: lgtm, size/XS, approved

#795 just: add build arg to pass in related images to bundle dockerfile
  Justfile
Labels: lgtm, size/XS, approved

#796 add a just target to build images serially
  Justfile
Labels: lgtm, size/XS, approved

#800 fix lints and remove old controller
  Justfile
  cmd/das-scheduler/main.go
  pkg/cmd/scheduler/cmd.go
  pkg/operator/controllers/instaslice/instaslice.go
  pkg/operator/operator.go
Labels: lgtm, size/L, approved

#803 regenerate codegen clients
  pkg/generated/applyconfiguration/dasoperator/v1alpha1/dasoperatorspec.go
Labels: size/S, lgtm, approved

#804 update components on pkg/generated changes
  .tekton/instaslice-daemonset-next-pull-request.yaml
  .tekton/instaslice-daemonset-next-push.yaml
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
  .tekton/instaslice-scheduler-next-pull-request.yaml
  .tekton/instaslice-scheduler-next-push.yaml
  .tekton/instaslice-webhook-next-pull-request.yaml
  .tekton/instaslice-webhook-next-push.yaml
Labels: size/S, lgtm, approved

#810 rbac: align scheduler ClusterRole permissions with operator RBAC
  bindata/assets/instaslice-operator/scheduler_rbac.clusterrole.yaml
Labels: lgtm, size/XS, approved

#813 build the operator on bindata/ changes
  .tekton/instaslice-operator-next-pull-request.yaml
  .tekton/instaslice-operator-next-push.yaml
Labels: lgtm, size/XS, approved

#826 Add OCP minimum version note in README
  README.md
Labels: lgtm, size/XS, approved

#789 Add deployment in e2e
  test/e2e/e2e.go
  test/test-deployment.yaml
Labels: lgtm, size/L, approved

#785 scheduler: ignore GPUs with staged allocationclaims
  pkg/scheduler/plugins/mig/mig.go
  pkg/scheduler/plugins/mig/mig_test.go
  test/e2e/e2e.go
Labels: lgtm, size/L, approved

#831 OCPNODE-3492: Add conditions to make sure webhook service is ready before executing e2e
  test/e2e/e2e.go
Labels: lgtm, jira/valid-reference, size/M, approved
